### ISSUE TITLE
Validate inline JavaScript syntax

### ISSUE THREAD

**Issue by AlbinoGeek** [xiphias/meteor-jade#2]
This was not an error when using mquandalle:meteor-jade .

``` console
View.coffee:1
  Uncaught TypeError: Cannot read property 'helpers' of undefined
    (anonymous function) @ View.coffee:1
    (anonymous function) @ View.coffee:1
```

Line 1 of View.coffee is:

``` coffee
Template.ProjectView.helpers
```

Which would be entirely valid, as "View.jade" is a file in the same directory:

``` jade
template(name='ProjectView')
  .ui.top.attached.message
    .ui.header Viewing Project {{project.name}}
    p (by {{fetchUserName project.owner}}
```

This seems like a bug where your package doesn't process the jade files before the coffeescript is called, thus resulting in an error since the template is not yet defined.

**Comment by AlbinoGeek** [comment]
Even if the file `View.jade` is renamed to `ProjectView.tpl.jade` and the first line removed, it still errors.

**Comment by AlbinoGeek** [comment]
Confirmed the issue is in this package, as even if the coffee is renamed to `z ProjectView.coffee` ; it is still executed before the jade is ready, therefore the template has not yet been created (and still errors.)

**Comment by AlbinoGeek** [comment]
Isolated this bug better:
- If the file is named `*.tpl.jade` the template name is **NOT CORRECT**
- If the file is renamed to `*.coffee.tpl.jade` it starts working again.

**Comment by AlbinoGeek** [comment]
More interesting fun:
- If the file is named *.jade , It simply doesn't end up on the client.
- If the file is named *.tpl.jade , there is no way to use a helper in an if block:

Both cause client errors:

``` jade
    if {{currentView 'Stories'}}
    if currentView 'Stories'
```

``` console
Uncaught SyntaxError: Unexpected token {
```

Generated JS:

``` js
Template["View"].helpers({
  _jade_line21: function() {
    return ({{currentView 'Stories'}});
  }
});
Template["View"].helpers({
  _jade_line21: function() {
    return (currentView 'Stories');
  }
});
```

**Comment by AlbinoGeek** [comment]
#### If the file is named `ProjectView.coffee.tpl.jade` exactly, it **works**:

``` jade
  .ui.bottom.attached.segment
    if currentView 'Stories'
      +ProjectStories
    if currentView 'Estimate'
      +ProjectStoryEstimate
    if currentView 'Sprints'
      +ProjectStorySprints
```

**Comment by xiphias** [comment]
*.jade should also work.
when you are using coffee.tpl.jade, the template name will be the start of the file name.
If you're not using tpl, the template name should be specified.
I couldn't reproduce the bug in the original form.
Could you please create a github repo with the smallest version of the bug? (the Meteor bug reporting document suggests this for bug reporting as well).

This works for me:

view.jade:

``` jade
body
    +ProjectView

template(name='ProjectView')
  .ui.top.attached.message
    .ui.header Viewing Project #{counter}
```

bug2.js:

``` javascript
if (Meteor.isClient) {
  Template.ProjectView.helpers({
    counter: function () {
      return 2;
    }
  });

}
```

**Comment by AlbinoGeek** [comment]
@xiphias 
Instead attempt to create a file named `View.tpl.jade`.

I'll make a repo with the bug shortly.

**Comment by xiphias** [comment]
View.tpl.jade creates a template called View. This is how it's intended and documented as well.

**Comment by xiphias** [comment]
Please read this part of the documentation: https://github.com/xiphias/meteor-jade-coffee#unwrapped-templates

**Comment by AlbinoGeek** [comment]
It will make more sense in the repo, there are some very odd bugs here in minimal land.

**Comment by AlbinoGeek** [comment]
Here we go: https://github.com/AlbinoGeek/itsabug

**Comment by AlbinoGeek** [comment]
Full Console Output:

``` console
[[[[[ \itsabug ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20151030-10:02:31.135(-7)? (STDERR) ReferenceError: Template is not defined
W20151030-10:02:31.136(-7)? (STDERR)     at itsabug.coffee:1:1
W20151030-10:02:31.136(-7)? (STDERR)     at itsabug.coffee:1:1
W20151030-10:02:31.136(-7)? (STDERR)     at \itsabug\.meteor\local\build\programs\server\boot.js:242:10
W20151030-10:02:31.136(-7)? (STDERR)     at Array.forEach (native)
W20151030-10:02:31.136(-7)? (STDERR)     at Function._.each._.forEach (\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20151030-10:02:31.137(-7)? (STDERR)     at \itsabug\.meteor\local\build\programs\server\boot.js:137:5
```

**Comment by AlbinoGeek** [comment]
I have updated the issue title, as if you pull the sample repo; then **rename the file to add the .coffee extension , resulting in `hello.coffee.tpl.jade`** the system stops crashing.

**Comment by AlbinoGeek** [comment]
Found some more notes:

`api.use('templating', 'client');`

Having this in a package.js also fixes the issue, as it forces Templating to be ready on the client.

**Comment by AlbinoGeek** [comment]
I have updated the repo to no longer send coffee to the server (heh, my bad on that one)

I am still replicating the interesting client side bugs though:

``` console
hello.tpl.jade.js?0f1b6ee692c878bb93879d6719fb23f5c8cb0178:18
 Uncaught SyntaxError: Unexpected identifier

itsabug.coffee:1
Uncaught TypeError: Cannot set property 'rendered' of undefined
  (anonymous function) @ itsabug.coffee:1
  (anonymous function) @ itsabug.coffee:1

blaze.js:3119
Uncaught Error: No such template: hello
```

Generated hello.tpl.jade.js served to the client:

``` js
(function(){
Template.__checkName("hello");
Template["hello"] = new Template("Template.hello", (function() {
  var view = this;
  return [ HTML.Raw("<button>Click Me</button>"), Blaze.If(function() {
    return Spacebars.call(view.lookup("_jade_line3"));
  }, function() {
    return HTML.P("You haven't clicked the button.");
  }, function() {
    return HTML.P("You've pressed the button times.");
  }), HTML.STRONG(Blaze.View("lookup:counter", function() {
    return Spacebars.mustache(view.lookup("counter"));
  })) ];
}));
```

##### Please make sure to sync AlbinoGeek:itsabug up to commit 912a8fd37ca6d3187839b0a5866f9e5b4ed324f1 as this has the latest test case of "broken"

**Comment by xiphias** [comment]
I checked the problem, but it has nothing to do with the description.
You wrote this:

``` coffeescript
if not counter?
```

It is valid coffeescript but invalid JavaScript. The coffeescript compiler takes care of it for the coffeescript part. The problem is that the error is not shown, but I don't know if we can do something about it.

**Comment by AlbinoGeek** [comment]
Ahh, I see.  It's falling through to automatically add js.

I figured a file named `*.tpl.jade` wouldn't be rendered with inline JS...  since a file named `*.jade` isn't.

**Comment by xiphias** [comment]
*.jade is also rendered with inline JS.
We could use esprima or some other JS syntax validator actually: http://esprima.org/demo/validate.html

**Comment by AlbinoGeek** [comment]
-- moved this part to other issue and closed it. --

## 

We currently lose reactivity inside these anonymous helpers?

``` jade
if not counter?
  p You haven't clicked the button.
else
  p You've pressed the button #{counter} times.
```

The first message is always shown, even if counter does increment.  I updated the bug repo.

The @ or `this` workaround doesn't work here.  Specifying `if not @counter?` doesn't change the outcome (reactivity lost, even though `Session.get('counter')` returns 13, the message `You haven\'t clicked the button.` is still shown.
